version: '3'

services:
  tapo-P110-exporter:
    image: p110-exporter
    volumes:
       - ./tapo.yaml:/app/tapo.yaml:ro
    ports:
      - 9333:9333
    environment:
      - TAPO_EMAIL=YOUR@EMAIL.COM
      - TAPO_PASSWORD=CHANGE_ME
      - PORT=9333                 # (optional)
      - MAX_RETRY_COUNT=3         # (optional) Default is 3 but if set to '0' will not stop trying to reach the device
      - DEVICES=study=192.168.0.1:80,living_room=192.168.0.2:80 # (file overrride) if set devices are set form it not the file
